[package]
name = "pallet-etf"
version = "4.0.0-dev"
description = "FRAME pallet to store and manage IBE public params"
authors = ["Ideal Labs <https://github.com/ideal-lab5>"]
homepage = "https://idealabs.network"
edition = "2021"
license = "MIT-0"
publish = false
repository = "https://github.com/ideal-lab5/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = { version = "0.4.17", default-features = false }
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = [
	"derive",
] }
rand_chacha = { version = "0.3.1", default-features = false }

sp-ark-bls12-381 = { version = "0.4.0-beta", features=["curve"], default-features = false }
sp-ark-models = { version = "0.4.0", default-features = false }
ark-serialize = { version = "0.4.0", features = [ "derive" ], default-features = false }
ark-scale = { git = "https://github.com/w3f/ark-scale", features = ["hazmat"], default-features = false }
ark-bls12-381 = { version = "0.4.0", features = ["curve"], default-features = false }
sp-io = { version = "23.0.0", path = "../../../../primitives/io", default-features = false }
primitive-types = { version = "0.12.1", default-features = false }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
frame-benchmarking = { version = "4.0.0-dev", default-features = false, optional = true, path = "../../../../frame/benchmarking" }
frame-support = { version = "4.0.0-dev", default-features = false, path = "../../../../frame/support" }
frame-system = { version = "4.0.0-dev", default-features = false, path = "../../../../frame/system" }

sp-std = { version = "8.0.0", default-features = false, path = "../../../../primitives/std" }
sp-runtime = { version = "24.0.0", default-features = false, path = "../../../../primitives/runtime" }
sp-crypto-ec-utils = { version = "0.4.0", default-features = false, path = "../../../../primitives/crypto/ec-utils" }
sp-core = { version = "21.0.0", path = "../../../../primitives/core", default-features = false }

[dev-dependencies]
frame-support-test = { version = "3.0.0", path = "../../../../frame/support/test" }
array-bytes = {version = "4.1", default-features = false }
hex = "0.4"
ark-std = { version = "0.4.0", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"primitive-types/std",
	"sp-std/std",
	"sp-runtime/std",
	"sp-io/std",
	"sp-core/std",
	"rand_chacha/std",
	"sp-ark-bls12-381/std",
	"sp-crypto-ec-utils/std",
	"sp-ark-models/std",
	"ark-serialize/std",
	"ark-scale/std",
	"ark-bls12-381/std",
]
runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
try-runtime = ["frame-support/try-runtime"]
