[package]
name = "pallet-etf"
version = "4.0.0-dev"
description = "FRAME pallet to publish slot secrets"
authors = ["Ideal Labs <https://github.com/ideal-lab5>"]
homepage = "https://idealabs.network"
edition = "2021"
license = "MIT-0"
publish = false
repository = "https://github.com/ideal-lab5/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
log = "0.4.17"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = [
	"derive",
] }
primitive-types = { version = "0.12.1", default-features = false }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
frame-benchmarking = { version = "4.0.0-dev", default-features = false, optional = true, path = "../../../../frame/benchmarking" }
frame-support = { version = "4.0.0-dev", default-features = false, path = "../../../../frame/support" }
frame-system = { version = "4.0.0-dev", default-features = false, path = "../../../../frame/system" }

sp-inherents = { version = "4.0.0-dev", path = "../../../../primitives/inherents", default-features = false }

[dev-dependencies]
sp-core = { version = "21.0.0", path = "../../../../primitives/core" }
sp-io = { version = "23.0.0", path = "../../../../primitives/io" }
sp-runtime = { version = "24.0.0", path = "../../../../primitives/runtime" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"primitive-types/std",
	"sp-inherents/std",
]
runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
try-runtime = ["frame-support/try-runtime"]
